name = "MagicLinkage"
uuid = "7e46d71e-e3ca-4f00-8e51-0df20d7851f3"
authors = ["Zheng, Chaozhi <chaozhi@gmail.com>"]
version = "1.0.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GZip = "92fee26a-97fe-5a0c-ad85-20a5f3185b63"
HMM = "c4d39e30-e0dc-11e8-017e-e988672db4fe"
LRUCache = "8ac3fa9e-de4c-5943-b1dc-09c6b5f20637"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MagicBase = "6ad26e1e-5512-4da8-b5d5-c225deef5fa2"
MagicImpute = "d6bde97e-f571-11e8-0752-dd2c38cea685"
MagicLD = "0c97556f-f1e7-4237-8a80-7e7d9b59bb26"
MagicPrior = "368bb602-e3a8-4e4e-878d-f4f466b68000"
MagicReconstruct = "55d4db80-e0d1-11e8-3790-159c8f731041"
Pedigrees = "dee1165e-fbf6-11e8-0f95-8d2c8a112ef1"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[sources]
HMM = {rev = "main", subdir = "packages/HMM", url = "https://github.com/Biometris/RABBIT"}
MagicBase = {rev = "main", subdir = "packages/MagicBase", url = "https://github.com/Biometris/RABBIT"}
MagicImpute = {rev = "main", subdir = "packages/MagicImpute", url = "https://github.com/Biometris/RABBIT"}
MagicLD = {rev = "main", subdir = "packages/MagicLD", url = "https://github.com/Biometris/RABBIT"}
MagicPrior = {rev = "main", subdir = "packages/MagicPrior", url = "https://github.com/Biometris/RABBIT"}
MagicReconstruct = {rev = "main", subdir = "packages/MagicReconstruct", url = "https://github.com/Biometris/RABBIT"}
Pedigrees = {rev = "main", subdir = "packages/Pedigrees", url = "https://github.com/Biometris/RABBIT"}

[compat]
HMM = "1.0.0"
MagicBase = "1.0.0"
MagicImpute = "1.0.0"
MagicLD = "1.0.0"
MagicPrior = "1.0.0"
MagicReconstruct = "1.0.0"
Pedigrees = "1.0.0"
