name = "HMM"
uuid = "c4d39e30-e0dc-11e8-017e-e988672db4fe"
authors = ["Zheng, Chaozhi <chaozhi@gmail.com>"]
version = "1.0.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
